{
 "title": "Windows System Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Idle_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"windows-empa-monitoring-server\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Processor\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> map(fn: (r) => ({r with _value: 100.0 - r._value}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"windows-empa-monitoring-server\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> map(fn: (r) => ({r with _value: 16965120819.2  - r._value}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")  "
    }
   ]
  },
  {
   "title": "Disk (C:) Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Free_Space\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"windows-empa-monitoring-server\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> map(fn: (r) => ({r with _value: 100.0  - r._value}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk (C:) Used Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Free_Space\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"windows-empa-monitoring-server\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> map(fn: (r) => ({r with _value: 100.0  - r._value}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"windows-empa-monitoring-server\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> map(fn: (r) => ({r with _value: 16965120819.2  - r._value}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")  "
    }
   ]
  }
 ]
}